FROM golang:1.17.2-alpine3.14 AS builder

WORKDIR /usr/app

COPY . .

RUN go mod init hello && \
  go build

FROM scratch
WORKDIR /usr/app
COPY --from=builder /usr/app/hello .
CMD [ "/usr/app/hello" ]